# Generated by Django 4.2.3 on 2023-12-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='adhar_number',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='actor',
            name='pan_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='actor',
            name='sim_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
