# Generated by Django 4.2.8 on 2023-12-12 14:01

import company.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank', '0001_initial'),
        ('actor', '0001_initial'),
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pan_number', models.CharField(max_length=10)),
                ('pan_dob', models.DateField()),
                ('querry_filled', models.DateField(auto_now_add=True)),
                ('company_status', models.CharField(blank=True, choices=[('', 'Select Company Status'), ('applied', 'Applied'), ('aproved', 'Aproved'), ('querry', 'Querry'), ('querryFilled', 'Querry Filled'), ('rejected', 'Rejected')], default='', max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('isMaharashtra', models.BooleanField(blank=True, default=False, null=True)),
                ('state', models.CharField(choices=[('', 'Select State'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], default='', max_length=150)),
                ('pdfs', models.FileField(blank=True, null=True, upload_to=company.models.file_path)),
                ('company_type', models.CharField(choices=[('', 'Select Company Type'), ('A', 'Type A'), ('B', 'Type B')], default='', max_length=150)),
                ('actor', models.ManyToManyField(blank=True, to='actor.actor')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank.bank')),
                ('owner', models.ManyToManyField(blank=True, to='owner.owner')),
            ],
        ),
    ]
