# Generated by Django 4.2.3 on 2023-12-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_rename_company_type_company_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='pan_number',
            field=models.CharField(max_length=20),
        ),
    ]
