# Generated by Django 4.2.8 on 2023-12-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
        ('company', '0004_alter_company_pan_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='bank',
        ),
        migrations.AddField(
            model_name='company',
            name='bank',
            field=models.ManyToManyField(blank=True, to='bank.bank'),
        ),
    ]
