# Generated by Django 4.2.8 on 2023-12-21 20:06

import company.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_company_pdfs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='pdfs',
        ),
        migrations.CreateModel(
            name='PDF_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to=company.models.file_path)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='company.company')),
            ],
        ),
    ]
