export const ADD_DATA_REQUEST = 'ADD_DATA_REQUEST'
export const ADD_DATA_SUCCESS = 'ADD_DATA_SUCCESS'
export const ADD_DATA_ERROR = 'ADD_DATA_ERROR'

export const EDIT_DATA_REQUEST = 'EDIT_DATA_REQUEST'
export const EDIT_DATA_SUCCESS = 'EDIT_DATA_SUCCESS'
export const EDIT_DATA_ERROR = 'EDIT_DATA_ERROR'

export const GET_ALL_DATA_REQUEST = 'GET_ALL_DATA_REQUEST'
export const GET_ALL_DATA_SUCCESS = 'GET_ALL_DATA_SUCCESS'
export const GET_ALL_DATA_ERROR = 'GET_ALL_DATA_ERROR'

export const GET_DATA_REQUEST = 'GET_DATA_REQUEST'
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS'
export const GET_DATA_ERROR = 'GET_DATA_ERROR'

export const DELETE_DATA_REQUEST = 'DELETE_DATA_REQUEST'
export const DELETE_DATA_SUCCESS = 'DELETE_DATA_SUCCESS'
export const DELETE_DATA_ERROR = 'DELETE_DATA_ERROR'
