export const ADD_DATA_REQUEST = 'ADD_DATA_REQUEST'
export const ADD_DATA_SUCCESS = 'ADD_DATA_SUCCESS'
export const ADD_DATA_ERROR = 'ADD_DATA_ERROR'

export const GET_ALL_DATA_REQUEST = 'GET_ALL_DATA_REQUEST'
export const GET_ALL_DATA_SUCCESS = 'GET_ALL_DATA_SUCCESS'
export const GET_ALL_DATA_ERROR = 'GET_ALL_DATA_ERROR'
