# Generated by Django 4.2.8 on 2023-12-14 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owner_type',
            new_name='type',
        ),
    ]
