# Generated by Django 4.2.3 on 2023-12-14 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_rename_owner_type_owner_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='banker',
        ),
    ]
