# Generated by Django 4.2.3 on 2023-12-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_remove_owner_banker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='adhar_number',
            field=models.CharField(max_length=26),
        ),
        migrations.AlterField(
            model_name='owner',
            name='pan_number',
            field=models.CharField(max_length=20),
        ),
    ]
