# Generated by Django 4.2.8 on 2023-12-21 17:05

import django.contrib.postgres.fields
from django.db import migrations, models
import owner.models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_alter_owner_adhar_number_alter_owner_pan_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='pdfs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(blank=True, null=True, upload_to=owner.models.file_path), default=list, size=None),
        ),
    ]
