# Generated by Django 4.2.8 on 2023-12-21 18:59

from django.db import migrations, models
import owner.models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_alter_owner_pdfs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='pdfs',
            field=models.FileField(blank=True, null=True, upload_to=owner.models.file_path),
        ),
    ]
