# Generated by Django 4.2.8 on 2023-12-21 19:46

from django.db import migrations, models
import django.db.models.deletion
import owner.models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0010_alter_owner_pdfs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='pdfs',
        ),
        migrations.CreateModel(
            name='PDF_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to=owner.models.file_path)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='owner.owner')),
            ],
        ),
    ]
