# Generated by Django 4.2.8 on 2023-12-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ifsc', models.CharField(max_length=100)),
                ('ad_code', models.CharField(max_length=100)),
                ('swift_code', models.CharField(max_length=100)),
                ('banker', models.ManyToManyField(blank=True, to='banker.banker')),
            ],
        ),
    ]
